-- ============================================================================
-- REAL-STACK prelude for supabase/tests/00_audit_user_delete.sql, run by
-- scripts/stack/test_db_stack.sh inside the file's own BEGIN … ROLLBACK (as
-- supabase_admin, before the file), so nothing here survives the file.
--
-- The file deletes auth.users rows as service_role (tests.as_service()). The
-- shim grants that (supabase/shim/10_auth.sql: grant all on auth.users to
-- service_role); real Supabase does not: only supabase_auth_admin (GoTrue,
-- the owner) and postgres may DELETE there, so the file failed with 42501
-- "permission denied for table users" at its first delete and its remaining
-- assertions (FK ON DELETE SET NULL / write-once audit columns across every
-- domain, invite authors) never ran on the real schema.
--
-- Granting SELECT (the WHERE clause reads auth.users.id) and DELETE for this
-- transaction only restores the shim's privilege, so the rest of the file
-- proves the cascades against the REAL auth.users table
-- (GoTrue's own columns, triggers and FKs). The account-deletion path the
-- product actually uses — GoTrue's admin API, running as supabase_auth_admin —
-- is proven separately by scripts/stack/verify_stack.mjs.
-- LOCAL / CI ONLY.
-- ============================================================================
grant select, delete on auth.users to service_role;
