/** Document JSON as money_public_quote_json / money_public_invoice_json return it. */
import type { InvoiceJson, QuoteJson } from "./render.ts";

export const SHOP_JSON = {
  name: "Shine Auto Spa",
  slug: "shine",
  logo_path: null,
  email: "hello@shine.example",
  phone: "+1 205 555 0100",
  website: "https://shine.example",
  address_line1: "12 Oak St",
  address_line2: null,
  city: "Birmingham",
  region: "AL",
  postal_code: "35203",
  country: "US",
  timezone: "America/Chicago",
  currency: "usd",
};

export const QUOTE_JSON: QuoteJson = {
  shop: SHOP_JSON,
  quote: {
    number: 1042,
    status: "sent",
    valid_until: "2026-07-01",
    notes: "Thanks for choosing us.",
    terms: "50% deposit to book.",
    subtotal_cents: 45000,
    discount_cents: 5000,
    tax_rate_bps: 825,
    tax_cents: 3300,
    total_cents: 43300,
    sent_at: "2026-06-01T15:00:00Z",
    has_options: false,
    selected_option_id: null,
  },
  customer: { first_name: "Dana", last_name: "Ruiz", company: "Ruiz Fleet LLC" },
  vehicle: { year: 2021, make: "Honda", model: "Civic", trim: null, color: "Blue" },
  options: [],
  line_items: [
    {
      id: "l1",
      option_id: null,
      name: "Full detail",
      description: "Interior + exterior",
      vehicle_label: "2021 Honda Civic",
      quantity: 1,
      unit_price_cents: 40000,
      discount_cents: 0,
      total_cents: 40000,
      optional: false,
      selected: true,
    },
    {
      id: "l2",
      option_id: null,
      name: "Ceramic spray",
      description: null,
      vehicle_label: null,
      quantity: 2,
      unit_price_cents: 2500,
      discount_cents: 0,
      total_cents: 5000,
      optional: true,
      selected: false,
    },
  ],
};

export const INVOICE_JSON: InvoiceJson = {
  shop: SHOP_JSON,
  invoice: {
    number: 2001,
    status: "partially_paid",
    issued_at: "2026-06-02T15:00:00Z",
    due_at: "2026-06-16T05:00:00Z",
    paid_at: null,
    voided_at: null,
    notes: null,
    terms: "Due in 14 days.",
    subtotal_cents: 40000,
    discount_cents: 0,
    tax_rate_bps: 700,
    tax_cents: 2800,
    total_cents: 42800,
    amount_paid_cents: 20000,
    balance_cents: 22800,
    tip_cents: 1500,
    processing_cents: 0,
  },
  customer: { first_name: "Dana", last_name: "Ruiz", company: null },
  job: { number: 1042, scheduled_start: "2026-06-02T15:00:00Z" },
  vehicle: { year: 2021, make: "Honda", model: "Civic" },
  jobs: [{ number: 1042, date: "2026-06-02", vehicle_label: "2021 Honda Civic" }],
  line_items: [{
    name: "Full detail",
    description: null,
    vehicle_label: "2021 Honda Civic",
    job_number: 1042,
    quantity: 1,
    unit_price_cents: 40000,
    discount_cents: 0,
    total_cents: 40000,
  }],
  payments: [{
    kind: "deposit",
    method: "card",
    status: "succeeded",
    amount_cents: 20000,
    tip_cents: 1500,
    refunded_cents: 0,
    card_brand: "visa",
    card_last4: "4242",
    paid_at: "2026-06-01T16:00:00Z",
  }],
};
